// PEG grammar for Python

// -----------------------------------------------------------------------------
// Bison Configuration
// -----------------------------------------------------------------------------

%require "3.2"
%language "c++"

// We don't need a separate header for Bison locations.
%define api.location.file none

// Use a type-safe C++ variant for semantic values
%define api.value.type variant

// Have Bison generate the functions ‘make_TEXT’ and ‘make_NUMBER’, but also
// ‘make_YYEOF’, for the end of input.
%define api.token.constructor

// Generate the parser as `::pxcompiler::Parser`.
%define api.namespace { pxcompiler }
%define api.parser.class { Parser }

// Enable support for parser debugging
%define parse.trace true

// Generate location structs.
%locations


// Parameters to the parser and lexer.
//
// Parameters to the parser are stored therein as protected data members, and
// thus available to its methods.

// "inout" parameters passed to both the parser and the lexer.
%param {pxcompiler::Nonnull<pxcompiler::Arena*> arena}
%param {yyscan_t yyscanner}
%param {ParseAndLexContext& context}

// "out" parameter passed to the parser, where the AST is written.
%parse-param {std::optional<pxcompiler::ASTPtr>* ast}

%code top {
  #include <algorithm>
  #include <cstdarg>
  #include <cstdio>
  #include <cstdlib>
  #include <vector>

  #include "common/check.h"
  #include "parser/flex_bison/parser.h"
  #include "parser/flex_bison/parse_and_lex_context.h"
  #include "llvm/ADT/StringExtras.h"
  #include "llvm/Support/raw_ostream.h"
}  // %code top


%code requires {
  #include <optional>

  #include "ast/ast.h"
  #include "common/arena.h"
  #include "common/nonnull.h"
  #include "parser/flex_bison/semantics.h"
  #include "parser/flex_bison/parser.h"

  namespace pxcompiler {
  class ParseAndLexContext;
  }  // namespace pxcompiler

  typedef void* yyscan_t;
}  // %code requires


%code {
  void pxcompiler::Parser::error(const location_type&, const std::string& message) {
    context.RecordSyntaxError(message);
  }
}  // %code

%token <long long> integer_literal
%token <std::string> identifier
%token <std::string> sized_type_literal
%token <std::string> string_literal

%token
  // Most tokens have their spelling defined in lexer.lpp.
  // table-begin
  FALSE
  TRUE
  NONE
  AND
  AS
  ASSERT
  ASYNC
  AWAIT
  BREAK
  CLASS
  CONTINUE
  DEF
  DEL
  ELIF
  ELSE
  EXCEPT
  FINALLY
  FOR
  FROM
  GLOBAL
  IF
  IMPORT
  IN
  IS
  LAMBDA
  NONLOCAL
  NOT
  OR
  PASS
  RETURN
  TRY
  WHILE
  WITH
  YIELD
  ARROW
  AMPERSAND
  COLON
  COLON_BANG
  COMMA
  DOUBLE_ARROW
  EQUAL
  EQUAL_EQUAL
  LBRACE
  LPARENT
  LBRACKET
  MINUS
  PERIOD
  PLUS
  RBRACE
  RPARENT
  RBRACKET
  SELF
  SEMICOLON
  SLASH
  UNDERSCORE

  INDENT
  DEDENT
  NEWLINE
  COMMENT
  EOLCOMMENT
  TYPE_COMMENT

  // Used to track EOF.
  END_OF_FILE 0
;

%type <Nonnull<Statement*>> script_unit
%type <Nonnull<Statement*>> statement
%type <Nonnull<Statement*>> expression_statment
%type <Nonnull<Statement*>> single_line_statement
%type <Nonnull<Statement*>> multi_line_statement
%type <Nonnull<Statement*>> if_statement
%type <std::vector<Nonnull<Statement*>>> body_stmts
%type <std::vector<Nonnull<Statement*>>> statements1
%type <std::vector<Nonnull<Statement*>>> statements
%type <std::vector<Nonnull<Statement*>>> sep_statements
%type <std::vector<Nonnull<Statement*>>> single_line_statements
%type <std::vector<Nonnull<Statement*>>> single_line_multi_statements
%type <std::vector<Nonnull<Statement*>>> single_line_multi_statements_opt
%type <Nonnull<Expression*>> expr
%type <Nonnull<Name*>> id
%type <Nonnull<Expression*>> string

%type <std::vector<std::string>> sep
%type <std::string> sep_one

%start units

%%
// The order of rules does not matter in Bison (unlike in ANTLR). The
// precedence is specified not by the order but by %left and %right directives
// as well as with %dprec.

// ----------------------------------------------------------------------------
// Top level rules to be used for parsing.

// Higher %dprec means higher precedence
units
    : units script_unit   { RESULT($2); }
    | script_unit         { RESULT($1); }
    | sep
    ;

script_unit
    : statement
    ;

statements
    : INDENT statements1 DEDENT { $$ = $2; }
    ;

sep_statements
    : sep statements { $$ = $2; }
    ;

body_stmts
    : single_line_statements { $$ = $1; }
    | sep_statements { $$ = $1; }
    ;

statements1
    : statements1 statement { $$ = $1; LIST_ADD($$, $2); }
    | statement { LIST_NEW($$); LIST_ADD($$, $1); }
    ;

single_line_statements
    : single_line_multi_statements NEWLINE { $$ = $1; }
    | single_line_multi_statements COMMENT NEWLINE { $$ = $1; }
    | single_line_statement NEWLINE { LIST_NEW($$); LIST_ADD($$, $1); }
    | single_line_statement SEMICOLON NEWLINE {
        LIST_NEW($$); LIST_ADD($$, $1);
      }
    | single_line_statement SEMICOLON COMMENT NEWLINE {
        LIST_NEW($$); LIST_ADD($$, $1);
      }
    | single_line_statement COMMENT NEWLINE {
        LIST_NEW($$); LIST_ADD($$, $1);
      }
    ;

single_line_multi_statements
    : single_line_multi_statements_opt single_line_statement {
        $$ = $1; LIST_ADD($$, $2);
      }
    | single_line_multi_statements_opt single_line_statement SEMICOLON {
        $$ = $1; LIST_ADD($$, $2);
      }
    ;

single_line_multi_statements_opt
    : single_line_multi_statements_opt single_line_statement SEMICOLON {
        $$ = $1; LIST_ADD($$, $2);
      }
    | single_line_statement SEMICOLON {
        LIST_NEW($$); LIST_ADD($$, $1);
      }
    ;

statement
    : single_line_statement sep { $$ = $1; }
    | multi_line_statement
    | multi_line_statement sep { $$ = $1; }
    ;

single_line_statement
    : expression_statment
//    | assert_statement
//    | assignment_statement
//    | augassign_statement
//    | ann_assignment_statement
//    | pass_statement
//    | delete_statement
//    | return_statement
//    | raise_statement
//    | break_statement
//    | continue_statement
//    | import_statement
//    | global_statement
//    | if_statement_single
//    | nonlocal_statement
    ;

multi_line_statement
    : if_statement
//    | for_statement
//    | try_statement
//    | with_statement
//    | function_def
//    | class_def
//    | async_func_def
//    | async_for_stmt
//    | async_with_stmt
//    | while_statement
    ;

if_statement
    : IF expr COLON body_stmts {
        $$ = IF_STMT_01($2, $4, context.source_loc());
      }
    | IF expr COLON body_stmts ELSE COLON body_stmts {
        $$ = IF_STMT_02($2, $4, $7, context.source_loc());
      }
//    | KW_IF expr ":" body_stmts elif_statement {
//        $$ = IF_STMT_03($2, $4, $5, @$); }
    ;

expression_statment
    : expr { $$ = EXPR_01($1, context.source_loc()); }
    ;

string
    : string string_literal { $$ = STRING2($1, $2, context.source_loc()); } // TODO
    | string_literal { $$ = STRING1($1, context.source_loc()); }
    | id string_literal { $$ = STRING3($1, $2, context.source_loc()); }
    ;

expr
    : id { $$ = $1; }
    | integer_literal { $$ = INTEGER($1, context.source_loc()); }
    | string { $$ = $1; }
   // | TK_REAL { $$ = FLOAT($1, @$); }
   // | TK_IMAG_NUM { $$ = COMPLEX($1, @$); }
   // | TK_TRUE { $$ = BOOL(true, @$); }
   // | TK_FALSE { $$ = BOOL(false, @$); }
   // | KW_NONE { $$ = NONE(@$); }
   // | TK_ELLIPSIS { $$ = ELLIPSIS(@$); }
   // | "(" expr ")" { $$ = $2; }
   // | "(" ")" { $$ = TUPLE_EMPTY(@$); }
   // | function_call { $$ = $1; }
   // | subscription { $$ = $1; }
   // | "[" expr_list_opt "]" { $$ = LIST($2, @$); }
   // | "[" expr_list "," "]" { $$ = LIST($2, @$); }
   // | "{" expr_list "}" { $$ = SET($2, @$); }
   // | "{" expr_list "," "}" { $$ = SET($2, @$); }
   // | expr "." id { $$ = ATTRIBUTE_REF($1, $3, @$); }

   // | "{" "}" { $$ = DICT_01(@$); }
   // | "{" dict_list "}" { $$ = DICT_02($2, @$); }
   // | KW_AWAIT expr %prec AWAIT { $$ = AWAIT($2, @$); }
   // | KW_YIELD %prec YIELD { $$ = YIELD_01(@$); }
   // | KW_YIELD expr %prec YIELD { $$ = YIELD_02($2, @$); }
   // | id ":=" expr { $$ = NAMEDEXPR($1, $3, @$); }
   // | "*" expr { $$ = STARRED_ARG($2, @$); }

   // | expr "+" expr { $$ = BINOP($1, Add, $3, @$); }
   // | expr "-" expr { $$ = BINOP($1, Sub, $3, @$); }
   // | expr "*" expr { $$ = BINOP($1, Mult, $3, @$); }
   // | expr "/" expr { $$ = BINOP($1, Div, $3, @$); }
   // | expr "%" expr { $$ = BINOP($1, Mod, $3, @$); }
   // | "-" expr %prec UNARY { $$ = UNARY($2, USub, @$); }
   // | "+" expr %prec UNARY { $$ = UNARY($2, UAdd, @$); }
   // | "~" expr %prec UNARY { $$ = UNARY($2, Invert, @$); }
   // | expr "**" expr { $$ = BINOP($1, Pow, $3, @$); }
   // | expr "//" expr { $$ = BINOP($1, FloorDiv, $3, @$); }
   // | expr "@" expr { $$ = BINOP($1, MatMult, $3, @$); }

   // | expr "&" expr { $$ = BINOP($1, BitAnd, $3, @$); }
   // | expr "|" expr { $$ = BINOP($1, BitOr, $3, @$); }
   // | expr "^" expr { $$ = BINOP($1, BitXor, $3, @$); }
   // | expr "<<" expr { $$ = BINOP($1, LShift, $3, @$); }
   // | expr ">>" expr { $$ = BINOP($1, RShift, $3, @$); }

   // | expr "==" expr { $$ = COMPARE($1, Eq, $3, @$); }
   // | expr "!=" expr { $$ = COMPARE($1, NotEq, $3, @$); }
   // | expr "<" expr { $$ = COMPARE($1, Lt, $3, @$); }
   // | expr "<=" expr { $$ = COMPARE($1, LtE, $3, @$); }
   // | expr ">" expr { $$ = COMPARE($1, Gt, $3, @$); }
   // | expr ">=" expr { $$ = COMPARE($1, GtE, $3, @$); }
   // | expr "is" expr { $$ = COMPARE($1, Is, $3, @$); }
   // | expr "is not" expr { $$ = COMPARE($1, IsNot, $3, @$); }
   // | expr "in" expr { $$ = COMPARE($1, In, $3, @$); }
   // | expr "not in" expr { $$ = COMPARE($1, NotIn, $3, @$); }

   // | expr "and" expr { $$ = BOOLOP($1, And, $3, @$); }
   // | expr "or" expr { $$ = BOOLOP($1, Or, $3, @$); }
   // | "not" expr { $$ = UNARY($2, Not, @$); }

   // // Comprehension
   // | "[" expr comp_for_items "]" { $$ = LIST_COMP_1($2, $3, @$); }
   // | "{" expr comp_for_items "}" { $$ = SET_COMP_1($2, $3, @$); }
   // | "{" expr ":" expr comp_for_items "}" { $$ = DICT_COMP_1($2, $4, $5, @$); }

   // | ternary_if_statement { $$ = $1; }
   // | lambda_expression { $$ = $1; }
    ;

id
    : identifier { $$ = SYMBOL($1, context.source_loc()); }
    ;

sep
    : sep sep_one { $$ = $1; LIST_ADD($$, $2); }
    | sep_one { LIST_NEW($$); LIST_ADD($$, $1); }
    ;

sep_one
    : NEWLINE { $$ = std::string("newline"); }
    | COMMENT { $$ = std::string("comment"); }
    | SEMICOLON { $$ = std::string(";"); }
    ;

%%